### PR TITLE
Add orders api support

### PR DESCRIPTION
**Pull request by ety001**
Add support for grouped orders.

Detail: [https://github.com/bitshares/bitshares-core/pull/662](https://github.com/bitshares/bitshares-core/pull/662).

For https://github.com/bitshares/bitshares-ui/issues/1106.

### CODE REVIEW

**Comment by svk31** [comment]
I've made some changes to make it optional and updated the tests, but the tests are failing when connected to eu.nodes.bitshares.ws.

The api initializes correctly, but the calls fail with an assert exception:

image

**Comment by abitmore** [comment]
@svk31 seems eu.nodes is not running latest version of witness_node(`2.0.180328`), or not using default `config.ini`. Please check and it's best to update it. In the meanwhile, you can test with my public node ws://api.bts.mobi/ .

**Comment by abitmore** [comment]
@svk31 note:
* no need to replay after enabled `grouped_orders` plugin, but does need a restart;
* if you're using an api-access file, please add "orders_api" to it as well.

**Comment by svk31** [comment]
I merged this manually here: https://github.com/bitshares/bitsharesjs-ws/commit/d00716f4bb7c9e50b0ecabc0a2d0cb2fa40a2378

Not sure why Github doesn't register it as merged.

**Pull request closed without merging**
