### PR TITLE
Refactor repo

### PR DESCRIPTION
**Pull request by scientistnik**
in current repo, if you run `npm install`, you will look this:
image

Build files have size:
image

After update `babel` and `browserify` packages, we have:
image
and
image

After I started tests and look this (`npm run test`):
image

I added all public modules in browser version:
image

I try rewrite code with save all public methods. For result, all tests pass:
image

Now code more clear and simple to read.

Please consider merging!

### CODE REVIEW

**Comment by scientistnik** [comment]
@svk31 what do you think?

**Comment by sschiessl-bcp** [comment]
@jcalfee 
Does this spark your curiousity and creates interest in reviewing this (through a UI bounty)?

**Comment by jcalfee** [comment]
Thanks for the offer, can't commit to that right now.  The code changes do look better though.  Looks like some "build" files were removed so that makes this easier to audit.  Really needs testing, make sure each API type still works and of course any other functions that were changed.

The websocket library change appears to be the same implementation just with the "isomorphic" version (node & browser version) changed.  Double check that, if the websocket implementation changed that may cause something that only appears out in the field.

You could have a test installer released fist so people can try it.  Better to have some other changes in there too that they can actually see.  Call me out if you have any questions..

**Comment by sschiessl-bcp** [comment]
Can you please re-open this PR against the new https://github.com/bitshares/bitsharesjs-ws/tree/develop branch?

**Comment by abitmore** [comment]
@sschiessl-bcp done for you :)

**Comment by sschiessl-bcp** [comment]
Accepted, manually merged into develop to create release candidate for further testing.

**Comment by sschiessl-bcp** [comment]
https://www.npmjs.com/package/bitsharesjs-ws/v/3.0.0-rc1

**Pull request merged**
