### PR TITLE
upgrade node to v16, and upgrade dependencies

### PR DESCRIPTION
**Pull request by xiangxn**
upgrade node to v16, and upgrade dependencies
And unified use of yarn package management tools.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please replace (and test) all usage of npm within package.json, and I suggest we bump version to 6.0.0.

**Review by abitmore — COMMENTED** [review]
> ... bump version to 6.0.0

@sschiessl-bcp I think you mean to bump version of `bitsharesjs-ws` itself in order to be in line with bitshares-core? Generally I agree that it's a good idea. Do we need to add support for new APIs? Perhaps better do it with another PR?

**Comment by xiangxn** [comment]
Yarn has been completely replaced, and the new features will have an independent PR. @sschiessl-bcp

**Review by abitmore — COMMENTED** [review]
If I understood correctly, code in the `lib` and `build` directories was generated from `src`. Do we really want to add them into the repository?

**Comment by xiangxn** [comment]
> If I understood correctly, code in the `lib` and `build` directories was generated from `src`. Do we really want to add them into the repository?

It is needed when publishing the package, of course it is not strictly necessary, and then put the generated code in the publishing program. But it is not enough to quote github directly, because these packages will not be compiled in the referenced place, so it is more convenient to put in the library.

**Comment by sschiessl-bcp** [comment]
`lib` and `build` should indeed not be necessary. In what case do you need them checked in?

The `prepare` script is called when you do `yarn install bitsharesjs-ws`, which in turn will create those binaries after fetching the src.

**Comment by xiangxn** [comment]
> `lib` and `build` should indeed not be necessary. In what case do you need them checked in?
> 
> The `prepare` script is called when you do `yarn install bitsharesjs-ws`, which in turn will create those binaries after fetching the src.

`lib` is not built automatically, it is built locally and published to npmjs. When I use yarn add https://github.com/... if the lib is not built, it cannot be used. It is added here for convenience , You can ignore the contents of the `lib` and `build` directories when reviewing the code.

**Review by sschiessl-bcp — APPROVED** [review]

**Comment by sschiessl-bcp** [comment]
I changed base to develop, master will be done with new release

**Comment by xiangxn** [comment]
Ok, very good

**Comment by xiangxn** [comment]
I cleaned up the lib, if I want to use it in other places, just fork it and compile it, for example, use it in html

**Comment by xiangxn** [comment]
If there are no other problems with the update, you can send the version first.

**Comment by sschiessl-bcp** [comment]
> I cleaned up the lib, if I want to use it in other places, just fork it and compile it, for example, use it in html

In general lib and dist folders should not be necessary to check in since they are built automatically.

**Comment by sschiessl-bcp** [comment]
For completeness, I just tested and can confirm that both
 - npm install https://github.com/bitshares/bitsharesjs-ws.git
 - yarn add  https://github.com/bitshares/bitsharesjs-ws.git
 call the prepare script and thus build the lib folder.

**Pull request merged**
